### ISSUE TITLE
test deposit, transfer, withdraw

### ISSUE THREAD

**Issue by barryWhiteHat** [rollupnc/RollupNC#6]
We want to test all the main functionality

1. trausted setup
2. contract deployment (remember to include merkle tree where all leaves are zero)
3. deposit (we can skip this for now by hard coding merkle tree at deploy time)
4. transacton creation
5. proof generation
6. validate proof inside snark perform state transition
7. Do 4 to 6 again and send the funds back. 
8. withdraw all coins and empty the side chain (this can wait)

**Comment by fredlacs** [comment]
Couldn't assign myself to this issue, but looking into it!

**Comment by fredlacs** [comment]
Putting this on-hold until Deposit and Withdrawal functionalities are further developed.

**Comment by therealyingtong** [comment]
done in https://github.com/rollupnc/RollupNC/blob/master/test/1_end_to_end.js
